# Generated by Django 4.0.4 on 2022-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
